<html>
<head>
<meta http-equiv="Content-Language" content="zh-cn">
<meta http-equiv="Content-Type" content="text/html; charset=gbk">
<title>广告位</title>
<style type="text/css">
body { font-size: 12px; font-family: 宋体;margin: 0px;}
td { font-size: 12px; font-family: 宋体; line-height: 18px;}
a {color: #111111; text-decoration: none}
a:hover { color: #ff8c40; text-decoration: underline}
</style>
</head>
<body>
{$HtmlContent}
<br>
</body>
</html>